```{r message=FALSE, warning=FALSE}
# Import libraries
library(dplyr)
library(readr)
library(stringr)
library(data.table)
library(devtools)
load_all()

# Import COVIMOD data
covimod_data <- read_rds("../../data/COVIMOD/COVIMOD_data_2022-12-29.rds")

# Unpack data
dt_part <- data.table(covimod_data$part)
dt_hh <- data.table(covimod_data$hh)
dt_nhh <- data.table(covimod_data$nhh)
dt_pop <- data.table(covimod_data$pop)
```

### Preprocessing step
```{r}
# Count the number of previous participations for each participant
setkeyv(dt_part, cols = c("new_id", "wave"))
dt_part[, rep := seq_len(.N) - 1, by = .(new_id)]

# If age_strata is 85+ change it to 80-84
dt_part[age_strata == "85+", age_strata := "80-84"]
dt_hh[alter_age_strata == "85+", alter_age_strata := "80-84"]
dt_nhh[alter_age_strata == "85+", alter_age_strata := "80-84"]
```

```{r}
# Extract data for wave 20
dt_part <- dt_part[wave == 20]
dt_hh <- dt_hh[wave == 20]
dt_nhh <- dt_nhh[wave == 20]
```

```{r}
# Sort dt_part by new_id
dt_part <- dt_part[order(new_id)]

# Remove participants with missing values in the gender column
dt_part <- dt_part[!is.na(gender)]

# Remove participants with missing values in the age_strata column
dt_part <- dt_part[!is.na(age_strata)]

# Impute missing ages for children
dt_part <- fill_missing_child_ages(dt_part, seed = 123)
```

### Prepare contact count vector Y
```{r}
# Create a grid of all possible combinations of participant IDs and alter_age_strata
# Extract a sorted vector of unique participant IDs from dt_part
part_ids <- unique(dt_part$new_id)

# Extract a vector of unique alter_age_strata from dt_nhh without missing values
alter_age_strata <- unique(dt_nhh[!is.na(alter_age_strata), alter_age_strata])

# Create a data.table with all possible combinations of participant IDs and alter_age_strata
dt_grid <- data.table(expand.grid(new_id = part_ids, alter_age_strata = alter_age_strata))
print(nrow(dt_grid))

# Append the imp_age column of dt_part to dt_grid
dt_grid <- merge(dt_grid, dt_part[, .(new_id, imp_age)], by = "new_id", all.x = TRUE)
```

```{r}
# For nhh Count the number of rows (contacts) by participant and alter_age_strata
dt_nhh_sum <- dt_nhh[, .(y_nhh = .N), by = .(new_id, alter_age_strata)]

# For hh sum the number of rows (contacts) by participant and alter_age_strata
dt_hh_sum <- dt_hh[, .(y_hh = sum(hh_met_this_day)), by = .(new_id, alter_age_strata)]

# Merge dt_nhh_sum and dt_hh_sum to dt_grid by left join
dt_grid <- merge(dt_grid, dt_nhh_sum, by = c("new_id", "alter_age_strata"), all.x = TRUE)
dt_grid <- merge(dt_grid, dt_hh_sum, by = c("new_id", "alter_age_strata"), all.x = TRUE)

# Set NA in y_nhh and y_hh to 0
dt_grid[is.na(y_nhh), y_nhh := 0]
dt_grid[is.na(y_hh), y_hh := 0]

# Add the columns y_nhh and y_hh and save it in a new column named y
dt_grid[, y := y_nhh + y_hh]
```

```{r}
# Make participant IDX
dt_grid[, part_idx := .GRP, by = new_id]
```


## Prepare participant characteristics X
```{r}
### ===== Job =====
dt_part <- dt_part[, job := dplyr::case_when(
  age_strata == "0-4" & school == "None of the above" ~ "Raised-at-home-toddler",
  age_strata == "0-4" & job == "None of the above" ~ "Raised-at-home-toddler",
  is.na(job) & school == "Nursery or pre-school" ~ school,
  is.na(job) & school == "School" ~ "Student/Pupil",
  is.na(job) & age_strata %in% c("5-9", "10-14") ~ "Student/Pupil",
  TRUE ~ job)]

# Check if there are any NAs in job
dt_part[is.na(job)]

# Split the data into adults and children (to prevent multicolinearity)
dt_part <- dt_part[, edu := dplyr::case_when(
  job == "Student/Pupil" & age_strata == "5-9" ~ "Student/Pupil_6-9",
  job == "Nursery or pre-school" ~ "Nursery or pre-school_0-5",
  job == "Raised-at-home-toddler" ~ "Raised-at-home-toddler_0-5",
  age_strata %in% c("0-4", "5-9", "10-14") ~ paste(job, age_strata, sep = "_"),
  TRUE ~ "Adult")]

# Check if there are any NAs in job and edu
dt_part[is.na(job) | is.na(edu)]

### ===== Household size =====
# Truncate household size at 4
dt_part[, hh_size := ifelse(hh_p_incl_0 > 4, 4, hh_p_incl_0)]

### ===== Make design matrix =====
# Make design matrix for the dummy variables
var_names <- c("edu", "gender", "hh_size", "job")
dt_dummies <- fastDummies::dummy_cols(select(dt_part, all_of(var_names)),
                                      select_columns = var_names,
                                      remove_selected_columns = TRUE)

# Create a new column u15 that is TRUE if the participant is under 15 years old
dt_dummies$u15 <- dt_part$age_strata %in% c("0-4", "5-9", "10-14")

# Remove the columns that are not needed
dt_dummies <- dt_dummies %>%
  select(!c(edu_Adult, `job_Raised-at-home-toddler`, `job_Nursery or pre-school`)) %>%
  mutate(across(matches("job"), function(x) ifelse(u15, 0, x))) %>%
  select(!u15)
```

## Prepare job dummy
```{r}
jobs_of_interest <- c("edu_Nursery or pre-school_0-5",
                      "edu_Student/Pupil_6-9",
                      "edu_Student/Pupil_10-14",
                      "job_Self employed",
                      "job_Student/Pupil")

jobD <- as.matrix(select(dt_dummies, jobs_of_interest))
job_idx <- rep(0, nrow(jobD))
for (i in 1:nrow(jobD)) {
  if (sum(jobD[i,]) > 0) {
    job_idx[i] <- which(jobD[i,] > 0, arr.ind = TRUE)
  }
}
```

## Prepare indexes and maps
### Age and age strata index set
```{r}
dt_grid[, age_idx := imp_age + 1]
dt_grid[, age_idx := ifelse(age_idx > 85, 85, age_idx)]
dt_grid[, alter_age_strata_idx := as.numeric(alter_age_strata)]

age_idxset <- as.matrix(dt_grid[, .(age_idx, alter_age_strata_idx)])
```

### Age strata map
```{r}
age_strata_map <- make_age_strata_map(dt_grid$alter_age_strata, 85, 13)
```

## Prepare offsets
```{r}
grid <- as.data.table(expand.grid(age_idx = 1:85))
tmp <- distinct(dt_grid[, .(new_id, age_idx)])
tmp <- tmp[, .(N = .N), by = age_idx]
dt_N <- merge(grid, tmp, by = "age_idx", all.x = TRUE)
dt_N[, N := ifelse(is.na(N), 1, N)]

offN <- dt_N$N
```

```{r}

dt_pop <- dt_pop[, .(pop = sum(pop)), by = age]
offP <- dt_pop[age <= 84, pop]
```

```{r}
# ===== Contacts with missing age strata information =====
# In dt_nhh_sum and dt_hh_sum extract the rows where alter_age_strata is NA
dt_nhh_na <- dt_nhh_sum[is.na(alter_age_strata)]
dt_hh_na <- dt_hh_sum[is.na(alter_age_strata)]

# Remove the column alter_age_strata
dt_nhh_na[, alter_age_strata := NULL]
dt_hh_na[, alter_age_strata := NULL]

# ===== Group Contacts =====
# In dt_part, sum the values in columns Q75_u18_work to Q75_o64_else and save it as y_grp
SDcols <- colnames(dt_part)[str_detect(colnames(dt_part), "Q")]
dt_part[, y_grp := rowSums(.SD, na.rm = TRUE), .SDcols = SDcols]

# Extract the new_id and y_grp columns from dt_part and save it as dt_grp
dt_grp <- dt_part[, .(new_id, y_grp)]

# ===== Combine the three data.tables =====
dt_cnt_na <- merge(dt_grp, dt_hh_na, by = "new_id", all.x = TRUE)
dt_cnt_na <- merge(dt_cnt_na, dt_nhh_na, by = "new_id", all.x = TRUE)

dt_cnt_na[, `:=`(
  y_grp = ifelse(is.na(y_grp), 0, y_grp),
  y_hh = ifelse(is.na(y_hh), 0, y_hh),
  y_nhh = ifelse(is.na(y_nhh), 0, y_nhh))]

dt_cnt_na[, y_miss := y_grp + y_hh + y_nhh]

# ===== Compute group contact offset =====
dt_cnt_sum <- dt_grid[, .(y = sum(y)), by = new_id]
dt_cnt_sum <- merge(dt_cnt_sum, dt_cnt_na, by = "new_id", all.x = TRUE)
dt_cnt_sum[, S := y / (y + y_miss)]
dt_cnt_sum[is.nan(S), S := 1]
dt_cnt_sum[S == 0, S := 1/(1 + y_miss)]
```

## Zero-Inflation parameters
```{r}
non_zero_idx <- which(dt_grid$y > 0, arr.ind = TRUE)
zero_idx <- which(dt_grid$y == 0, arr.ind = TRUE)
```

## Gather and export data
```{r}
data <- list(
  Nobs = nrow(dt_grid),
  Npart = nrow(dt_part),
  Nzero = length(zero_idx),
  Nnonzero = length(non_zero_idx),
  
  A = 85,
  A2 = 85*(85 + 1)/2,
  C = 13,
  P = ncol(dt_dummies),
  J = max(job_idx),
  R = max(dt_part$rep + 1),
  
  Y = dt_grid$y,
  X = as.matrix(dt_dummies),
  job_idx = job_idx,
  rep_idx = dt_part$rep + 1,
  part_idx = dt_grid$part_idx,
  zero_idx = zero_idx,
  non_zero_idx = non_zero_idx,
  
  age_idxset = age_idxset,
  age_strata_map = age_strata_map,
  offN = offN,
  offP = offP,
  offS = dt_cnt_sum$S
)

saveRDS(data, "../../data/silver/covimod-wave-20.rds")
```

```{r}
mean(dt_grid[, .(y = sum(y)), by = new_id]$y)
```






