```{r}
library(dplyr)
library(readr)
library(purrr)
```

```{r}
out_dir <- "~/Imperial/covimod-fatigue-outputs"
results_dir <- file.path(out_dir, "results")

model_names <- c(
  "pois_norm_constrained",
  "pois_horseshoe_constrained",
  "zip_norm_constrained",
  "zip_horseshoe_constrained"
)

read_loo <- function(path, model_name) {
  file_path <- file.path(path, model_name, "LOO.rds")
  loo <- read_rds(file_path)
  loo_est <- as.data.frame(loo$estimates)
  loo_est$stat <- rownames(loo_est)
  rownames(loo_est) <- NULL
  loo_est$model_name <- model_name
  
  return(loo_est)
}

read_ppc <- function(path, model_name) {
  file_path <- file.path(path, model_name, "ppc.rds")
  ppc <- read_rds(file_path)
  ppc_stat <- data.frame(model_name = model_name, ppc = mean(ppc$inside_CI))
  
  return(ppc_stat)
}
```

```{r}
df_loo_summary <- map_dfr(model_names, ~read_loo(results_dir, .x))
df_loo_summary %>% filter(stat == "elpd_loo")
```
```{r}
df_ppc_summary <- map_dfr(model_names, ~read_ppc(results_dir, .x))
df_ppc_summary
```





