```{r}
library(tidyverse)
library(patchwork)
library(MASS)
library(pscl)
theme_set(theme_bw())

df <- read_rds("../data/silver/covimod_wave_4.rds")
```

```{r}
x <- seq(0, 5, length.out = 100)
y <- exp(1.5*x)/(1 + exp(1.5*x))

df <- data.frame(x, y)

ggplot(df, aes(x, y)) +
  geom_line(col = 6, linewidth = 1.2) +
  theme_minimal() +
  theme(
    axis.text = element_blank(),
    axis.title = element_blank()
  )

ggsave("~/Desktop/growth-curve.png", width = 28.07, height = 16.03, units = "cm")
```


Visualize the distribution of contact counts.
We observe a lot of outliers in the data.
We will remove those with more than 25 contact and visualize the distribution again.
```{r}
p1 <- ggplot(df, aes(x = y)) +
  geom_histogram(binwidth = 1)

# Remove outliers
p2 <- ggplot(filter(df, y < 25), aes(x = y)) +
  geom_histogram(binwidth = 1)

p1 + p2
```

```{r}
df_clean <- filter(df, y < 15)
df_clean <- filter(df_clean, repeat_status == 0)
```

```{r}
m1 <- glm.nb(y ~ age_strata, df_clean)
summary(m1)

df_pred <- data.frame(y = df_clean$y, y_pred = predict(m1, type = "response"))
plot(df_pred$y, df_pred$y_pred)
abline(0, 1, col = "red")
```
```{r}
m2 <- glm.nb(y ~ age_strata + gender, df_clean)
summary(m2)

df_pred <- data.frame(y = df_clean$y, y_pred = predict(m2, type = "response"))
plot(df_pred$y, df_pred$y_pred)
abline(0, 1, col = "red")
```
```{r}
m3 <- glm.nb(y ~ age_strata + gender + factor(hh_p_incl_0), df_clean)
summary(m3)

df_pred <- data.frame(y = df_clean$y, y_pred = predict(m3, type = "response"))
plot(df_pred$y, df_pred$y_pred)
abline(0, 1, col = "red")
```

```{r}
m4 <- glm.nb(y ~ age_strata + gender + factor(hh_p_incl_0) + dow + job, df_clean)
summary(m4)

df_pred <- data.frame(y = df_clean$y, y_pred = predict(m4, type = "response"))
plot(df_pred$y, df_pred$y_pred)
abline(0, 1, col = "red")
```
```{r}
m5 <- zeroinfl(y ~ age_strata + gender + factor(hh_p_incl_0) + dow + job, df_clean, dist = "negbin")
summary(m5)

df_pred <- data.frame(y = df_clean$y, y_pred = predict(m5, type = "response"))
plot(df_pred$y, df_pred$y_pred)
abline(0, 1, col = "red")

plot(density(df_pred$y_pred))
lines(density(df_pred$y))
```

