out_dir: "/rds/general/user/sd121/home/contact-survey-fatigue-outputs"
experiment_name: "negb_brc_m52_sim_ind"

data:
  fname: "preCOVID_ind.rds"

model:
  name: "negb_brc_m52_sim_ind"
  M1: 30
  M2: 30
  C1: 1.5
  C2: 1.5

mcmc:
  seed: 0
  iter_warmup: 500
  iter_sampling: 1000
  chains: 4
  parallel_chains: 4
  max_treedepth: 11
