out_dir: "/rds/general/user/sd121/home/contact-survey-fatigue-outputs"
experiment_name: "negb_brc_m52_wave_21_noadj"

data:
  fname: "covimod-wave-21.rds"

model:
  name: "negb_brc_m52_noadj"
  M1: 30
  M2: 30
  C1: 1.5
  C2: 1.5
  hatGamma: 2.32
  hatKappa: 0.635
  hatEta: 1.11
  
mcmc:
  seed: 0
  iter_warmup: 500
  iter_sampling: 1000
  chains: 4
  parallel_chains: 4
  max_treedepth: 11
