out_dir: "/rds/general/user/sd121/home/contact-survey-fatigue-outputs"

model:
  name: "pois_longit_invquad"
  
mcmc:
  seed: 0
  iter_warmup: 500
  iter_sampling: 1000
  chains: 4
  parallel_chains: 4
  max_treedepth: 11
