out_dir: "/rds/general/user/sd121/home/contact-survey-fatigue-outputs"
experiment_name: "pois_longit_logistic"

model:
  name: "pois_longit_logistic"
  
mcmc:
  seed: 0
  iter_warmup: 500
  iter_sampling: 2000
  chains: 4
  parallel_chains: 4
  max_treedepth: 12
  
