out_dir: "~/Imperial/contact-surveys-fatigue-outputs"

model:
  name: "pois_longit_gp"
  
mcmc:
  seed: 0
  iter_warmup: 500
  iter_sampling: 1000
  chains: 4
  parallel_chains: 4
  max_treedepth: 11
