out_dir: "~/Imperial/covimod-fatigue-outputs"

model:
  name: "zip_norm_constrained"
  
mcmc:
  seed: 0
  iter_warmup: 500
  iter_sampling: 1000
  chains: 4
  parallel_chains: 4
  max_treedepth: 11

plot:
  baseline_effects:
    width: 22
    height: 10
  repeat_effects:
    width: 22
    height: 10
