out_dir: "~/Imperial/covimod-fatigue-outputs"

model:
  name: "zip_horseshoe_balanced"
  p0: 1
  scale_slab: 2

mcmc:
  seed: 0
  iter_warmup: 500
  iter_sampling: 1000
  chains: 4
  parallel_chains: 4
  max_treedepth: 12

plot:
  baseline_effects:
    width: 22
    height: 10
  repeat_effects:
    width: 22
    height: 10
