out_dir: "/rds/general/user/sd121/home/contact-survey-fatigue-outputs"
experiment_name: "zip_horesehoe_medium_shrinkage"

model:
  name: "zip_horseshoe_constrained"
  p0: 3
  scale_slab: 3

mcmc:
  seed: 0
  iter_warmup: 500
  iter_sampling: 1000
  chains: 4
  parallel_chains: 4
  max_treedepth: 11

plot:
  baseline_effects:
    width: 22
    height: 10
  repeat_effects:
    width: 22
    height: 10
