out_dir: "/rds/general/user/sd121/home/contact-survey-fatigue-outputs"
experiment_name: "zip_horseshoe_balanced_24"

model:
  name: "zip_horseshoe_balanced"
  p0: 24
  hs_df: 2
  hs_df_global: 2
  hs_df_slab: 4
  scale_slab: 3

mcmc:
  seed: 0
  iter_warmup: 500
  iter_sampling: 2000
  chains: 4
  parallel_chains: 4
  max_treedepth: 13
  adapt_delta: 0.99

plot:
  baseline_effects:
    width: 22
    height: 10
  repeat_effects:
    width: 22
    height: 10
