project:
  type: website

website:
  title: "Contact Survey Fatigue"
  navbar:
    left:
      - href: index.qmd
        text: Home
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Longitudinal Analysis"
        contents:
          - text: Response Functions
          - file: response-functions.qmd
          


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-block-border-left: "#31BAE9"
    code-block-bg: true
    highlight-style: pygments



