#' Indices to make a symmetric matrix from a lower triangular matrix
#'
#' @param A
#'
#' @return A vector of indices
#' @export
#'
#' @details
#' Suppose there is a vector containing the elements of a lower triangular matrix arranged in column-major order.
#' This function generates the indices required to obtain a vector containing the elements of a symmetric full matrix,
#' generated by copying the lower triangular matrix to the upper triangular part.
make_sym_from_lowertri_idx <- function(A) {
  index_set <- rep(NA, A)
  n <- 1

  for (j in 1:A) {
    for (i in 1:A) {
      if (i >= j) {
        index_set[n] <- i + (j - 1)*A - j*(j - 1)/2
      } else {
        index_set[n] <- j + (i - 1)*A - i*(i - 1)/2
      }

      n <- n + 1
    }
  }

  return(index_set)
}
